# Generated by Django 3.1.5 on 2021-01-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210127_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.BooleanField(default=False),
        ),
    ]
