# Generated by Django 3.1.5 on 2021-01-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bill_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
