# Generated by Django 3.1.5 on 2021-02-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resultdouble',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='resultfirst',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='resultsecound',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='events.team'),
        ),
    ]
