# Generated by Django 3.1.5 on 2021-02-02 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210202_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='live',
        ),
        migrations.RemoveField(
            model_name='event',
            name='resultdouble',
        ),
        migrations.RemoveField(
            model_name='event',
            name='resultfirst',
        ),
        migrations.RemoveField(
            model_name='event',
            name='resultsecound',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='team2',
        ),
        migrations.AddField(
            model_name='event',
            name='coefficient',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=False)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.sport')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='events.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='events.team')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.match'),
        ),
    ]
