# Generated by Django 3.1.5 on 2021-02-02 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210202_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.match'),
        ),
    ]
