# Generated by Django 3.1.5 on 2021-02-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(default='0:0', max_length=200),
        ),
    ]
