# Generated by Django 3.1.5 on 2021-02-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
