# Generated by Django 3.1.5 on 2021-02-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_match_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='sport_id',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
