# Generated by Django 3.1.6 on 2021-02-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210210_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
