# Generated by Django 3.1.6 on 2021-02-11 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210212_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='events.match'),
        ),
    ]
