# Generated by Django 3.1.6 on 2021-02-12 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0014_bet_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BetToExpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField()),
                ('win', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betsExpress', to='events.event')),
                ('express', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='events.express')),
                ('match', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='matchsExpress', to='events.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersExpress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
