# Generated by Django 3.1.6 on 2021-02-12 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_bettoexpress_express'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettoexpress',
            name='user',
        ),
        migrations.AddField(
            model_name='express',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usersExpress', to=settings.AUTH_USER_MODEL),
        ),
    ]
